// convex/seedData.ts
import { mutation } from "./_generated/server";

export const seedDatabase = mutation({
  handler: async (ctx) => {
    const now = Date.now();

    // Seed Projects
    const projects = [
      {
        projectCode: "TS-ERP-2024",
        name: "TeamSystem ERP Evolution",
        description:
          "Next-generation ERP system for Italian SMEs with cloud-native architecture",
        businessUnitId: "bu-erp-001",
        businessUnitName: "Market Specific Solution",
        status: "in_progress",
        priority: "high",
        startDate: "2024-01-15",
        estimatedDuration: 18,
        teamSize: 12,
        teamLead: "mario.rossi@teamsystem.com",
        teamMembers: [
          "mario.rossi@teamsystem.com",
          "giulia.bianchi@teamsystem.com",
          "luca.verdi@teamsystem.com",
        ],
        technologies: [
          "Java",
          "Spring Boot",
          "PostgreSQL",
          "React",
          "TypeScript",
          "Docker",
          "Kubernetes",
        ],
        domain: "Enterprise Resource Planning",
        projectType: "Product Development",
        location: "Pesaro, Italy",
        repositoryUrl: "https://github.com/teamsystem/erp-evolution",
        jiraProjectKey: "TSERP",
        totalCommits: 2847,
        totalJiraTickets: 456,
        totalJiraTicketsClosed: 389,
        recentCommits: [
          {
            commitHash: "a1b2c3d4",
            message: "Add inventory management module",
            author: "luca.verdi@teamsystem.com",
            timestamp: now - 3600000,
          },
        ],
        recentJiraTickets: [
          {
            ticketId: "TSERP-234",
            title: "Implement multi-currency support",
            status: "In Progress",
            assignee: "giulia.bianchi@teamsystem.com",
            updatedAt: now - 7200000,
          },
        ],
        createdAt: now,
        updatedAt: now,
        isActive: true,
      },
      {
        projectCode: "TS-HR-2024",
        name: "Digital HR Platform",
        description:
          "Cloud HR management system with payroll integration for Italian labor laws",
        businessUnitId: "bu-hr-002",
        businessUnitName: "Enterprise",
        status: "in_progress",
        priority: "high",
        startDate: "2023-09-01",
        estimatedDuration: 24,
        teamSize: 15,
        teamLead: "francesca.marino@teamsystem.com",
        teamMembers: [
          "francesca.marino@teamsystem.com",
          "alessandro.conti@teamsystem.com",
          "sara.ferrari@teamsystem.com",
        ],
        technologies: [
          "C#",
          ".NET Core",
          "Azure",
          "Angular",
          "SQL Server",
          "Redis",
        ],
        domain: "Human Resources",
        projectType: "SaaS Platform",
        location: "Milan, Italy",
        repositoryUrl: "https://github.com/teamsystem/hr-platform",
        jiraProjectKey: "TSHR",
        totalCommits: 3542,
        totalJiraTickets: 589,
        totalJiraTicketsClosed: 512,
        createdAt: now,
        updatedAt: now,
        isActive: true,
      },
      {
        projectCode: "TS-TAX-2024",
        name: "Tax Compliance Suite",
        description:
          "Automated tax calculation and filing system compliant with Italian regulations",
        businessUnitId: "bu-tax-003",
        businessUnitName: "Enterprise",
        status: "planning",
        priority: "medium",
        startDate: "2025-01-01",
        estimatedDuration: 12,
        teamSize: 8,
        teamLead: "giuseppe.romano@teamsystem.com",
        teamMembers: [
          "giuseppe.romano@teamsystem.com",
          "elena.greco@teamsystem.com",
        ],
        technologies: [
          "Python",
          "Django",
          "PostgreSQL",
          "Vue.js",
          "Celery",
          "RabbitMQ",
        ],
        domain: "Tax & Accounting",
        projectType: "Compliance System",
        location: "Rome, Italy",
        jiraProjectKey: "TSTAX",
        totalCommits: 0,
        totalJiraTickets: 124,
        totalJiraTicketsClosed: 0,
        createdAt: now,
        updatedAt: now,
        isActive: true,
      },
      {
        projectCode: "TS-DOC-2024",
        name: "Document Management System",
        description:
          "Digital document archiving and management solution for Italian businesses",
        businessUnitId: "bu-doc-004",
        businessUnitName: "Market Specific Solution",
        status: "in_progress",
        priority: "medium",
        startDate: "2024-03-01",
        estimatedDuration: 15,
        teamSize: 10,
        teamLead: "marco.esposito@teamsystem.com",
        teamMembers: [
          "marco.esposito@teamsystem.com",
          "chiara.lombardi@teamsystem.com",
        ],
        technologies: [
          "Node.js",
          "MongoDB",
          "React",
          "ElasticSearch",
          "AWS S3",
        ],
        domain: "Document Management",
        projectType: "SaaS Platform",
        location: "Bologna, Italy",
        repositoryUrl: "https://github.com/teamsystem/doc-management",
        jiraProjectKey: "TSDOC",
        totalCommits: 1856,
        totalJiraTickets: 312,
        totalJiraTicketsClosed: 267,
        createdAt: now,
        updatedAt: now,
        isActive: true,
      },
    ];

    const projectIds = [];
    for (const project of projects) {
      const id = await ctx.db.insert("projects", project);
      projectIds.push(id);
    }

    // Seed Employees
    const employees = [
      {
        employeeCode: "TS-001",
        firstName: "Mario",
        lastName: "Rossi",
        email: "mario.rossi@teamsystem.com",
        avatar: "https://i.pravatar.cc/150?u=mario.rossi",
        location: "Pesaro, Italy",
        languages: ["Italian", "English", "Spanish"],
        businessUnitId: "bu-erp-001",
        businessUnitName: "ERP Solutions",
        department: "Engineering",
        role: "Senior Software Architect",
        skills: [
          {
            name: "Java",
            category: "Programming",
            proficiencyLevel: "Expert",
            yearsOfExperience: 12,
          },
          {
            name: "Spring Boot",
            category: "Framework",
            proficiencyLevel: "Expert",
            yearsOfExperience: 8,
          },
          {
            name: "Microservices",
            category: "Architecture",
            proficiencyLevel: "Advanced",
            yearsOfExperience: 7,
          },
          {
            name: "PostgreSQL",
            category: "Database",
            proficiencyLevel: "Advanced",
            yearsOfExperience: 10,
          },
        ],
        softSkills: [
          {
            name: "Leadership",
            category: "Management",
            level: "Advanced",
          },
          {
            name: "Communication",
            category: "Interpersonal",
            level: "Expert",
          },
        ],
        interests: [
          "Cloud Architecture",
          "DevOps",
          "Road Cycling",
          "Mountain Hiking",
        ],
        activities: [
          "Tech Meetup Speaker",
          "Code Review Champion",
          "Company Cycling Team Captain",
          "Pesaro Half Marathon Runner",
          "Organizes weekly team bike rides",
        ],
        yearsOfExperience: 15,
        yearsInTeamSystem: 8,
        currentProjects: ["TS-ERP-2024"],
        pastProjects: ["TS-ERP-2021", "TS-CRM-2020"],
        totalCommits: 4523,
        totalJiraTasksClosed: 892,
        recentCommits: [
          {
            commitHash: "e5f6g7h8",
            message: "Refactor authentication service",
            repository: "erp-evolution",
            timestamp: now - 1800000,
          },
        ],
        recentJiraTasks: [
          {
            taskId: "TSERP-123",
            title: "Design billing module architecture",
            status: "Closed",
            closedAt: now - 86400000,
          },
        ],
        createdAt: now,
        updatedAt: now,
        isActive: true,
      },
      {
        employeeCode: "TS-002",
        firstName: "Giulia",
        lastName: "Bianchi",
        email: "giulia.bianchi@teamsystem.com",
        avatar: "https://i.pravatar.cc/150?u=giulia.bianchi",
        location: "Pesaro, Italy",
        languages: ["Italian", "English", "French"],
        businessUnitId: "bu-erp-001",
        businessUnitName: "ERP Solutions",
        department: "Engineering",
        role: "Full Stack Developer",
        skills: [
          {
            name: "TypeScript",
            category: "Programming",
            proficiencyLevel: "Advanced",
            yearsOfExperience: 5,
          },
          {
            name: "React",
            category: "Framework",
            proficiencyLevel: "Expert",
            yearsOfExperience: 6,
          },
          {
            name: "Node.js",
            category: "Backend",
            proficiencyLevel: "Advanced",
            yearsOfExperience: 5,
          },
        ],
        softSkills: [
          {
            name: "Problem Solving",
            category: "Technical",
            level: "Advanced",
          },
          {
            name: "Creativity",
            category: "Innovation",
            level: "Advanced",
          },
        ],
        interests: [
          "UX Design",
          "Web Performance",
          "Photography",
          "Yoga",
          "Travel",
        ],
        activities: [
          "Women in Tech Advocate",
          "Company Yoga Instructor",
          "Photography Club Member",
          "Organizes team wellness sessions",
          "Weekend hiking enthusiast",
          "Travel blog contributor",
        ],
        yearsOfExperience: 7,
        yearsInTeamSystem: 4,
        currentProjects: ["TS-ERP-2024"],
        pastProjects: ["TS-PORTAL-2022"],
        totalCommits: 2156,
        totalJiraTasksClosed: 534,
        createdAt: now,
        updatedAt: now,
        isActive: true,
      },
      {
        employeeCode: "TS-003",
        firstName: "Francesca",
        lastName: "Marino",
        email: "francesca.marino@teamsystem.com",
        avatar: "https://i.pravatar.cc/150?u=francesca.marino",
        location: "Milan, Italy",
        languages: ["Italian", "English", "German"],
        businessUnitId: "bu-hr-002",
        businessUnitName: "HR & Payroll",
        department: "Engineering",
        role: "Technical Lead",
        skills: [
          {
            name: "C#",
            category: "Programming",
            proficiencyLevel: "Expert",
            yearsOfExperience: 10,
          },
          {
            name: ".NET Core",
            category: "Framework",
            proficiencyLevel: "Expert",
            yearsOfExperience: 8,
          },
          {
            name: "Azure",
            category: "Cloud",
            proficiencyLevel: "Advanced",
            yearsOfExperience: 6,
          },
          {
            name: "SQL Server",
            category: "Database",
            proficiencyLevel: "Advanced",
            yearsOfExperience: 9,
          },
        ],
        softSkills: [
          {
            name: "Team Management",
            category: "Management",
            level: "Advanced",
          },
          {
            name: "Agile Coaching",
            category: "Process",
            level: "Advanced",
          },
        ],
        interests: ["Cloud Native", "AI/ML", "Running", "Cooking", "Tennis"],
        activities: [
          "Scrum Master Certification",
          "Mentor for Junior Developers",
          "Milan Marathon 2024 Finisher",
          "Company Running Club Leader",
          "Tennis league player",
          "Cooking class organizer",
          "Charity run participant",
        ],
        yearsOfExperience: 12,
        yearsInTeamSystem: 6,
        currentProjects: ["TS-HR-2024"],
        pastProjects: ["TS-HR-2021", "TS-PAYROLL-2019"],
        totalCommits: 3789,
        totalJiraTasksClosed: 756,
        createdAt: now,
        updatedAt: now,
        isActive: true,
      },
      {
        employeeCode: "TS-004",
        firstName: "Alessandro",
        lastName: "Conti",
        email: "alessandro.conti@teamsystem.com",
        avatar: "https://i.pravatar.cc/150?u=alessandro.conti",
        location: "Milan, Italy",
        languages: ["Italian", "English"],
        businessUnitId: "bu-hr-002",
        businessUnitName: "HR & Payroll",
        department: "Engineering",
        role: "Backend Developer",
        skills: [
          {
            name: "C#",
            category: "Programming",
            proficiencyLevel: "Advanced",
            yearsOfExperience: 6,
          },
          {
            name: "ASP.NET",
            category: "Framework",
            proficiencyLevel: "Advanced",
            yearsOfExperience: 6,
          },
          {
            name: "Azure DevOps",
            category: "DevOps",
            proficiencyLevel: "Intermediate",
            yearsOfExperience: 4,
          },
        ],
        softSkills: [
          {
            name: "Analytical Thinking",
            category: "Technical",
            level: "Advanced",
          },
          {
            name: "Teamwork",
            category: "Collaboration",
            level: "Advanced",
          },
        ],
        interests: [
          "Distributed Systems",
          "Gaming",
          "Soccer",
          "Basketball",
          "E-sports",
        ],
        activities: [
          "Company Soccer Team Forward",
          "5-a-side soccer captain",
          "Gaming tournament organizer",
          "Basketball pickup games coordinator",
          "Coaches youth soccer on weekends",
          "E-sports team member",
          "FIFA tournament champion 2024",
        ],
        yearsOfExperience: 6,
        yearsInTeamSystem: 3,
        currentProjects: ["TS-HR-2024"],
        pastProjects: ["TS-API-2023"],
        totalCommits: 1834,
        totalJiraTasksClosed: 423,
        createdAt: now,
        updatedAt: now,
        isActive: true,
      },
      {
        employeeCode: "TS-005",
        firstName: "Giuseppe",
        lastName: "Romano",
        email: "giuseppe.romano@teamsystem.com",
        avatar: "https://i.pravatar.cc/150?u=giuseppe.romano",
        location: "Rome, Italy",
        languages: ["Italian", "English"],
        businessUnitId: "bu-tax-003",
        businessUnitName: "Tax & Compliance",
        department: "Engineering",
        role: "Principal Engineer",
        skills: [
          {
            name: "Python",
            category: "Programming",
            proficiencyLevel: "Expert",
            yearsOfExperience: 11,
          },
          {
            name: "Django",
            category: "Framework",
            proficiencyLevel: "Expert",
            yearsOfExperience: 9,
          },
          {
            name: "Data Modeling",
            category: "Architecture",
            proficiencyLevel: "Advanced",
            yearsOfExperience: 10,
          },
        ],
        softSkills: [
          {
            name: "Strategic Thinking",
            category: "Leadership",
            level: "Advanced",
          },
          {
            name: "Mentoring",
            category: "Teaching",
            level: "Expert",
          },
        ],
        interests: [
          "FinTech",
          "Compliance Tech",
          "Chess",
          "Wine Tasting",
          "History",
        ],
        activities: [
          "Open Source Contributor",
          "Chess club president",
          "Wine appreciation course graduate",
          "Local chess tournament winner",
          "Historical walking tours enthusiast",
          "Sommelier Level 1 certified",
          "Teaches Python workshops",
        ],
        yearsOfExperience: 13,
        yearsInTeamSystem: 7,
        currentProjects: ["TS-TAX-2024"],
        pastProjects: ["TS-TAX-2022", "TS-FINANCE-2020"],
        totalCommits: 4012,
        totalJiraTasksClosed: 834,
        createdAt: now,
        updatedAt: now,
        isActive: true,
      },
      {
        employeeCode: "TS-006",
        firstName: "Luca",
        lastName: "Verdi",
        email: "luca.verdi@teamsystem.com",
        avatar: "https://i.pravatar.cc/150?u=luca.verdi",
        location: "Pesaro, Italy",
        languages: ["Italian", "English"],
        businessUnitId: "bu-erp-001",
        businessUnitName: "ERP Solutions",
        department: "Engineering",
        role: "DevOps Engineer",
        skills: [
          {
            name: "Kubernetes",
            category: "Container Orchestration",
            proficiencyLevel: "Advanced",
            yearsOfExperience: 5,
          },
          {
            name: "Docker",
            category: "Containerization",
            proficiencyLevel: "Expert",
            yearsOfExperience: 6,
          },
          {
            name: "AWS",
            category: "Cloud",
            proficiencyLevel: "Advanced",
            yearsOfExperience: 5,
          },
          {
            name: "Terraform",
            category: "Infrastructure as Code",
            proficiencyLevel: "Advanced",
            yearsOfExperience: 4,
          },
        ],
        softSkills: [
          {
            name: "Automation",
            category: "Efficiency",
            level: "Expert",
          },
        ],
        interests: [
          "Cloud Infrastructure",
          "Automation",
          "Rock Climbing",
          "Camping",
          "Drone Flying",
        ],
        activities: [
          "Indoor rock climbing twice a week",
          "Outdoor climbing trips organizer",
          "Drone photography hobbyist",
          "Camping and backpacking enthusiast",
          "Mountain rescue volunteer",
          "Company outdoor adventure club founder",
        ],
        yearsOfExperience: 8,
        yearsInTeamSystem: 5,
        currentProjects: ["TS-ERP-2024"],
        pastProjects: ["TS-INFRA-2022"],
        totalCommits: 2945,
        totalJiraTasksClosed: 612,
        createdAt: now,
        updatedAt: now,
        isActive: true,
      },
      {
        employeeCode: "TS-007",
        firstName: "Sara",
        lastName: "Ferrari",
        email: "sara.ferrari@teamsystem.com",
        avatar: "https://i.pravatar.cc/150?u=sara.ferrari",
        location: "Milan, Italy",
        languages: ["Italian", "English", "Portuguese"],
        businessUnitId: "bu-hr-002",
        businessUnitName: "HR & Payroll",
        department: "Engineering",
        role: "Frontend Developer",
        skills: [
          {
            name: "Angular",
            category: "Framework",
            proficiencyLevel: "Expert",
            yearsOfExperience: 7,
          },
          {
            name: "TypeScript",
            category: "Programming",
            proficiencyLevel: "Advanced",
            yearsOfExperience: 6,
          },
          {
            name: "CSS/SASS",
            category: "Styling",
            proficiencyLevel: "Expert",
            yearsOfExperience: 8,
          },
        ],
        softSkills: [
          {
            name: "Attention to Detail",
            category: "Quality",
            level: "Expert",
          },
        ],
        interests: [
          "UI/UX Design",
          "Accessibility",
          "Swimming",
          "Pilates",
          "Gardening",
        ],
        activities: [
          "Competitive swimmer",
          "Pilates instructor certification",
          "Urban gardening enthusiast",
          "Accessibility advocate",
          "Masters swimming team member",
          "Community garden volunteer",
          "Design system maintainer",
        ],
        yearsOfExperience: 9,
        yearsInTeamSystem: 5,
        currentProjects: ["TS-HR-2024"],
        pastProjects: ["TS-UI-2022", "TS-DESIGN-2021"],
        totalCommits: 2678,
        totalJiraTasksClosed: 589,
        createdAt: now,
        updatedAt: now,
        isActive: true,
      },
      {
        employeeCode: "TS-008",
        firstName: "Marco",
        lastName: "Esposito",
        email: "marco.esposito@teamsystem.com",
        avatar: "https://i.pravatar.cc/150?u=marco.esposito",
        location: "Bologna, Italy",
        languages: ["Italian", "English", "French"],
        businessUnitId: "bu-doc-004",
        businessUnitName: "Document Solutions",
        department: "Engineering",
        role: "Team Lead",
        skills: [
          {
            name: "Node.js",
            category: "Backend",
            proficiencyLevel: "Expert",
            yearsOfExperience: 9,
          },
          {
            name: "MongoDB",
            category: "Database",
            proficiencyLevel: "Advanced",
            yearsOfExperience: 7,
          },
          {
            name: "React",
            category: "Framework",
            proficiencyLevel: "Advanced",
            yearsOfExperience: 6,
          },
        ],
        softSkills: [
          {
            name: "Leadership",
            category: "Management",
            level: "Advanced",
          },
        ],
        interests: [
          "Full Stack Development",
          "Volleyball",
          "Music Production",
          "Craft Beer",
        ],
        activities: [
          "Volleyball team setter",
          "Music producer and DJ",
          "Craft beer tasting club member",
          "Beach volleyball tournaments",
          "Electronic music events organizer",
          "Local brewery tour guide",
          "Company band keyboard player",
        ],
        yearsOfExperience: 11,
        yearsInTeamSystem: 6,
        currentProjects: ["TS-DOC-2024"],
        pastProjects: ["TS-DOC-2021", "TS-ARCHIVE-2020"],
        totalCommits: 3421,
        totalJiraTasksClosed: 701,
        createdAt: now,
        updatedAt: now,
        isActive: true,
      },
      {
        employeeCode: "TS-009",
        firstName: "Elena",
        lastName: "Greco",
        email: "elena.greco@teamsystem.com",
        avatar: "https://i.pravatar.cc/150?u=elena.greco",
        location: "Rome, Italy",
        languages: ["Italian", "English", "Spanish"],
        businessUnitId: "bu-tax-003",
        businessUnitName: "Tax & Compliance",
        department: "Engineering",
        role: "Senior Python Developer",
        skills: [
          {
            name: "Python",
            category: "Programming",
            proficiencyLevel: "Advanced",
            yearsOfExperience: 8,
          },
          {
            name: "FastAPI",
            category: "Framework",
            proficiencyLevel: "Advanced",
            yearsOfExperience: 4,
          },
          {
            name: "Data Science",
            category: "Analytics",
            proficiencyLevel: "Intermediate",
            yearsOfExperience: 5,
          },
        ],
        softSkills: [
          {
            name: "Research",
            category: "Analysis",
            level: "Advanced",
          },
        ],
        interests: [
          "Machine Learning",
          "Tax Technology",
          "Dancing",
          "Theatre",
          "Painting",
        ],
        activities: [
          "Salsa dancing instructor",
          "Community theatre performer",
          "Watercolor painting classes",
          "Dance studio regular",
          "Art exhibition visitor",
          "Local theatre group member",
          "Tango workshop participant",
        ],
        yearsOfExperience: 9,
        yearsInTeamSystem: 4,
        currentProjects: ["TS-TAX-2024"],
        pastProjects: ["TS-ANALYTICS-2023"],
        totalCommits: 2234,
        totalJiraTasksClosed: 478,
        createdAt: now,
        updatedAt: now,
        isActive: true,
      },
      {
        employeeCode: "TS-010",
        firstName: "Chiara",
        lastName: "Lombardi",
        email: "chiara.lombardi@teamsystem.com",
        avatar: "https://i.pravatar.cc/150?u=chiara.lombardi",
        location: "Bologna, Italy",
        languages: ["Italian", "English"],
        businessUnitId: "bu-doc-004",
        businessUnitName: "Document Solutions",
        department: "Engineering",
        role: "Full Stack Developer",
        skills: [
          {
            name: "JavaScript",
            category: "Programming",
            proficiencyLevel: "Advanced",
            yearsOfExperience: 6,
          },
          {
            name: "Vue.js",
            category: "Framework",
            proficiencyLevel: "Advanced",
            yearsOfExperience: 5,
          },
          {
            name: "ElasticSearch",
            category: "Search Engine",
            proficiencyLevel: "Intermediate",
            yearsOfExperience: 3,
          },
        ],
        softSkills: [
          {
            name: "Collaboration",
            category: "Teamwork",
            level: "Advanced",
          },
        ],
        interests: [
          "Web Development",
          "Skiing",
          "Book Club",
          "Baking",
          "Podcasts",
        ],
        activities: [
          "Alpine skiing enthusiast",
          "Company book club organizer",
          "Amateur baker and pastry maker",
          "Podcast host - Tech & Life",
          "Winter sports trips coordinator",
          "Baking competition participant",
          "Literary festival volunteer",
        ],
        yearsOfExperience: 7,
        yearsInTeamSystem: 4,
        currentProjects: ["TS-DOC-2024"],
        pastProjects: ["TS-SEARCH-2022"],
        totalCommits: 1987,
        totalJiraTasksClosed: 445,
        createdAt: now,
        updatedAt: now,
        isActive: true,
      },
    ];

    for (const employee of employees) {
      await ctx.db.insert("employees", employee);
    }

    return {
      success: true,
      message: "Database seeded successfully with sports and activities!",
      projectsCreated: projects.length,
      employeesCreated: employees.length,
    };
  },
});
